### ISSUE TITLE
confusion about self-training

### ISSUE THREAD

**Issue by UCAS-GYX** [Ajmal70/IJCAI_2021_Continual_Crowd_Counting_Challenge#1]
Hey, I am confused about the way of self-training in your code. If pseudo label is generated successively and then is used to do self-training, the loss would be 0. In that case, the gradient will not be updated. From my point of view, you should generate pseudo labels for all unlabeled samples, and then conduct self-training with origin labeled training samples and pseudo samples.
By the way, I have submitted some beseline results to the challenge website. However, only the result with the highest error is shown in the Leaderboard. Hence, the order is reversed.
https://github.com/Ajmal70/IJCAI_2021_Continual_Crowd_Counting_Challenge/blob/62d506fcf1f009d4d7caea06da7dd560f109c4e4/main.py#L151-L164

**Comment by Ajmal70** [comment]
Hi, the self training idea is more like an example for the participants. Considering your input, we are also limited by the original labelled  data too, i.e., we are not using it during a validation part. The participants are open to implement their own self training approach though.

Currently, eval.ai is ranking based on highest value. However, we will resolve this issue hopefully. Alternatively we can switch ranking manually from the rank tab.
